// SPDX-License-Identifier: CERN-OHL-S-2.0
import {distance,fitCircle,definitions,measurements,status} from './geometry.mjs';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');
let photo=null,steps=[],index=-1,config=null,result=null,zoom=1,offset=[0,0],drag=null,worker=null,busy=false,automatic=false;
const reqs=definitions.map(r=>[...r]),colors=['#f6b950','#58ded0','#f6b950','#58ded0','#e995db'];
const names=['Aislamiento · lado 1','Conductor · lado 1','Aislamiento · lado 2','Conductor · lado 2','Puente central'];
const name=i=>i===0?'Calibración de la regla':`Par ${Math.floor((i-1)/5)+1} · ${names[(i-1)%5]}`;
const needed=i=>i===0||(i-1)%5===4?2:config.points;
const fmt=v=>v.toFixed(3);
const reqText=r=>r[1]==='none'?'Sin requisito':r[1]==='nominal'?`${fmt(r[2])} ± ${fmt(r[3])}`:`${r[1]==='min'?'≥':'≤'} ${fmt(r[2])}`;
function message(text){$('instruction').textContent=text;}
function controls(){const active=index>=0&&index<steps.length;$('accept').disabled=busy||!active||steps[index].length<needed(index);$('undo').disabled=busy||index<0;$('redraw').disabled=busy||!active;for(const id of ['start','auto','file','demo'])$(id).disabled=busy||(!photo&&['start','auto'].includes(id));$('edit').disabled=busy||index<0;$('steps').disabled=busy||index<0;for(const id of ['csv','png','pdf'])$(id).disabled=!result||busy;$('progress').textContent=busy?'D E T E C C I Ó N  E N  C U R S O':index<0?'LISTO PARA COMENZAR':active?`PASO ${index+1} DE ${steps.length} · ${steps[index].length} / ${needed(index)} PUNTOS`:'MEDICIÓN COMPLETA';}
function instruction(){controls();if(index>=0&&index<steps.length)message(`${name(index)}. ${steps[index].length>=needed(index)?'Revisa y arrastra los puntos; luego acepta el paso.':index===0?`Marca los extremos del tramo de ${config.mm} mm.`:'Marca puntos distribuidos sobre el contorno indicado.'}`);}
function fit(){if(!photo)return;zoom=Math.min(canvas.clientWidth/photo.width,canvas.clientHeight/photo.height)*.94;offset=[(canvas.clientWidth-photo.width*zoom)/2,(canvas.clientHeight-photo.height*zoom)/2];draw();}
function resize(){const dpr=window.devicePixelRatio||1;canvas.width=Math.round(canvas.clientWidth*dpr);canvas.height=Math.round(canvas.clientHeight*dpr);if(photo)fit();else draw();}
new ResizeObserver(resize).observe($('viewport'));
function overlay(c,scale=1,active=true){
 const last=Math.min(index,steps.length-1);
 for(let i=0;i<=last;i++){const pts=steps[i];if(!pts?.length)continue;const color=i===0?'#fff':colors[(i-1)%5];c.strokeStyle=color;c.fillStyle=color;c.lineWidth=2/scale;c.setLineDash(i===index?[6/scale,4/scale]:[]);
 if(i===0||(i-1)%5===4){if(pts.length===2){c.beginPath();c.moveTo(...pts[0]);c.lineTo(...pts[1]);c.stroke();if(i===0){c.font=`${12/scale}px sans-serif`;for(const t of [0,.5,1]){const p=pts[0].map((v,k)=>v+(pts[1][k]-v)*t);c.textAlign=t===0?'right':t===1?'left':'center';c.fillText(`${config.mm*t} mm`,p[0]+(t===0?-5:t===1?5:0)/scale,p[1]+(t===.5?22:-10)/scale);c.textAlign='left';}}}}
 else if(pts.length>=3){try{const {c:center,r}=fitCircle(pts);c.beginPath();c.arc(...center,r,0,Math.PI*2);c.stroke();if((i-1)%5===0){c.font=`bold ${14/scale}px sans-serif`;c.fillText(`P${Math.floor((i-1)/5)+1}`,center[0]-r,center[1]-r-8/scale);}}catch{}}
 c.setLineDash([]);if(active&&i===index)for(const p of pts){c.beginPath();c.arc(...p,5/scale,0,Math.PI*2);c.fillStyle='white';c.fill();c.strokeStyle='#164f48';c.stroke();}
 }
}
function draw(){const dpr=window.devicePixelRatio||1;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);if(!photo)return;ctx.translate(...offset);ctx.scale(zoom,zoom);ctx.drawImage(photo,0,0);overlay(ctx,zoom);}
async function loadImage(src,label){const next=new Image();next.onload=()=>{photo=next;steps=[];index=-1;result=null;config=null;$('results').replaceChildren();$('resultnote').textContent='Los resultados aparecerán al completar y aceptar todos los pasos.';$('empty').style.display='none';$('filename').textContent=label;$('viewtitle').textContent=`${next.width} × ${next.height} PX`;$('steps').replaceChildren(new Option('Primero inicia una medición'));fit();controls();message('Imagen lista. Configura la regla y elige un modo de medición.');if(src.startsWith('blob:'))URL.revokeObjectURL(src);};next.onerror=()=>{message('No se pudo abrir la imagen. Prueba con PNG o JPG.');if(src.startsWith('blob:'))URL.revokeObjectURL(src);};next.src=src;}
$('file').onchange=e=>{const f=e.target.files[0];if(f)loadImage(URL.createObjectURL(f),f.name);e.target.value='';};
$('demo').onclick=()=>{const c=document.createElement('canvas');c.width=1100;c.height=650;const x=c.getContext('2d');x.fillStyle='#202c30';x.fillRect(0,0,c.width,c.height);x.fillStyle='#85aa51';x.fillRect(320,295,340,60);for(const [cx,color] of [[340,'#71ad60'],[680,'#d6c456']]){x.beginPath();x.arc(cx,325,145,0,7);x.fillStyle=color;x.fill();x.beginPath();x.arc(cx,325,60,0,7);x.fillStyle='#bd865a';x.fill();x.strokeStyle='#e3b78d';x.lineWidth=1.5;for(let i=0;i<18;i++){const a=i*2.4,r=48*Math.sqrt(i/18);x.beginPath();x.arc(cx+Math.cos(a)*r,325+Math.sin(a)*r,9,0,7);x.stroke();}}x.fillStyle='#fff';x.fillRect(100,550,100,4);x.font='18px sans-serif';x.fillText('0,5 mm',110,587);x.fillText('MUESTRA SINTÉTICA · 200 px/mm',100,80);$('pairs').value=1;$('ruler').value=.5;loadImage(c.toDataURL(),'Ejemplo sintético · escala de 0,5 mm');};
function start(auto){if(!photo||busy)return;const count=Number($('pairs').value),points=Number($('points').value),mm=Number($('ruler').value);if(!Number.isInteger(count)||count<1||count>12||!Number.isInteger(points)||points<3||points>32||!Number.isFinite(mm)||mm<=0){message('Revisa la configuración: 1–12 pares, 3–32 puntos y una regla positiva.');return;}if(index>=0&&!confirm('¿Reiniciar la medición? Se borrarán los puntos actuales.'))return;config={count,points:auto?8:points,mm};automatic=auto;index=0;steps=Array.from({length:1+count*5},()=>[]);result=null;$('results').replaceChildren();$('resultnote').textContent='Medición en curso. Acepta todos los pasos para obtener resultados.';updateOptions();instruction();draw();canvas.focus();}
$('start').onclick=()=>start(false);$('auto').onclick=()=>start(true);
function updateOptions(){$('steps').replaceChildren(...steps.map((_,i)=>new Option(name(i),i)));$('steps').value=Math.min(index,steps.length-1);for(const opt of $('steps').options)opt.disabled=Number(opt.value)>index;}
function detect(){busy=true;controls();message('Cargando el motor automático y analizando la imagen. La primera carga puede tardar unos minutos.');worker=new Worker('detector-worker.js');const source=document.createElement('canvas');const ratio=Math.min(1,1280/Math.max(photo.width,photo.height));source.width=Math.round(photo.width*ratio);source.height=Math.round(photo.height*ratio);const c=source.getContext('2d');c.drawImage(photo,0,0,source.width,source.height);const data=c.getImageData(0,0,source.width,source.height);const timeout=setTimeout(()=>finish({error:'Se agotó el tiempo de carga. Puedes continuar manualmente.'}),240000);function finish(data){clearTimeout(timeout);worker.terminate();worker=null;busy=false;if(data.proposals){steps.splice(1,steps.length-1,...data.proposals.map(ps=>ps.map(p=>[p[0]*photo.width/source.width,p[1]*photo.height/source.height])));instruction();}else{instruction();message(`No fue posible detectar todos los contornos. Continúa manualmente. ${data.error?.split('\n').pop()||''}`);}draw();}worker.onmessage=e=>finish(e.data);worker.onerror=()=>finish({error:'No se pudo cargar el motor. Comprueba la conexión.'});worker.postMessage({pixels:data.data.buffer,width:source.width,height:source.height,count:config.count},[data.data.buffer]);}
function accept(){if($('accept').disabled)return;try{const p=steps[index];if(index===0||(index-1)%5===4){if(distance(...p)<1e-6)throw Error('Los extremos deben ser distintos.');}else fitCircle(p);if(index===steps.length-1)measurements(steps,config.mm);index++;updateOptions();if(index===steps.length){renderResults();message('Medición completa. Puedes corregir los pasos o descargar el informe.');}else instruction();draw();if(index===1&&automatic){automatic=false;detect();}}catch(e){message(e.message);}}
$('accept').onclick=accept;
function invalidate(){result=null;$('results').replaceChildren();$('resultnote').textContent='Revisión en curso: vuelve a aceptar los pasos para recalcular.';}
$('edit').onclick=()=>{index=Number($('steps').value);invalidate();updateOptions();instruction();draw();};
function undo(){if(busy||index<0)return;if(index===steps.length||!steps[index].length){if(index>0)index--;}else steps[index].pop();invalidate();updateOptions();instruction();draw();}
$('undo').onclick=undo;$('redraw').onclick=()=>{steps[index]=[];instruction();draw();};
function point(e){const r=canvas.getBoundingClientRect();return [(e.clientX-r.left-offset[0])/zoom,(e.clientY-r.top-offset[1])/zoom];}
canvas.onpointerdown=e=>{if(!photo||busy)return;canvas.focus();canvas.setPointerCapture(e.pointerId);const p=point(e);if(e.shiftKey||e.button===1){drag={pan:true,x:e.clientX,y:e.clientY,offset:[...offset]};return;}if(e.button!==0||index<0||index>=steps.length)return;const found=steps[index].findIndex(q=>distance(p,q)<10/zoom);if(found>=0)drag={point:found};else if(steps[index].length<needed(index)&&p[0]>=0&&p[1]>=0&&p[0]<=photo.width&&p[1]<=photo.height){steps[index].push(p);drag={point:steps[index].length-1};}instruction();draw();};
canvas.onpointermove=e=>{if(!drag)return;if(drag.pan)offset=[drag.offset[0]+e.clientX-drag.x,drag.offset[1]+e.clientY-drag.y];else steps[index][drag.point]=point(e).map((v,k)=>Math.max(0,Math.min(v,k===0?photo.width:photo.height)));draw();};
canvas.onpointerup=canvas.onpointercancel=()=>{drag=null;};canvas.oncontextmenu=e=>{e.preventDefault();undo();};
function magnify(f,x=canvas.clientWidth/2,y=canvas.clientHeight/2){if(!photo)return;const next=Math.max(.01,Math.min(30,zoom*f));offset=[x-(x-offset[0])*next/zoom,y-(y-offset[1])*next/zoom];zoom=next;draw();}
canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();magnify(e.deltaY<0?1.15:1/1.15,e.clientX-r.left,e.clientY-r.top);},{passive:false});$('zoomin').onclick=()=>magnify(1.25);$('zoomout').onclick=()=>magnify(.8);$('fit').onclick=fit;
canvas.onkeydown=e=>{if(e.code==='Space'){e.preventDefault();accept();}else if(e.key==='Backspace'||(e.ctrlKey&&e.key==='z')){e.preventDefault();undo();}else if(e.key.toLowerCase()==='f')fit();};
for(const [i,r] of reqs.entries()){const label=document.createElement('label');label.textContent=`${r[0]} (mm)`;const select=document.createElement('select');for(const [v,t] of [['none','Sin requisito'],['nominal','Nominal ± tolerancia'],['min','Mínimo'],['max','Máximo']])select.add(new Option(t,v));select.value=r[1];const row=document.createElement('div');row.className='fields';const val=document.createElement('input'),tol=document.createElement('input');for(const input of [val,tol]){input.type='number';input.min='0';input.step='.001';}val.value=r[2];tol.value=r[3];val.setAttribute('aria-label',`${r[0]} valor`);tol.setAttribute('aria-label',`${r[0]} tolerancia`);function change(){if(!Number.isFinite(val.valueAsNumber)||val.valueAsNumber<0||!Number.isFinite(tol.valueAsNumber)||tol.valueAsNumber<0){message('Las tolerancias deben ser números positivos o cero.');return;}r[1]=select.value;r[2]=val.valueAsNumber;r[3]=tol.valueAsNumber;val.disabled=r[1]==='none';tol.disabled=r[1]!=='nominal';if(result)renderResults();}select.onchange=val.onchange=tol.onchange=change;row.append(val,tol);label.append(select,row);$('requirements').append(label);change();}
function renderResults(){result=measurements(steps,config.mm);$('results').replaceChildren();for(const [i,values] of result.values.entries()){const tr=document.createElement('tr'),state=status(values,reqs[i]);for(const text of [definitions[i][0],fmt(Math.min(...values)),fmt(Math.max(...values)),fmt(values.reduce((a,b)=>a+b,0)/values.length),reqText(reqs[i]),state]){const td=document.createElement('td');td.textContent=text;tr.append(td);}tr.lastChild.className=state==='FUERA'?'fail':'ok';$('results').append(tr);}$('resultnote').textContent=`${config.count} par(es) · ${fmt(result.scale)} px/mm · Todas las dimensiones en mm · Estados evaluados sobre cada valor individual.`;controls();}
function download(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('csv').onclick=()=>{const rows=[['Analizador de sección de cables'],['Regla (mm)',config.mm],['Escala (px/mm)',result.scale],[],['Medida','Mínimo','Máximo','Media','Requisito','Estado']];result.values.forEach((v,i)=>rows.push([definitions[i][0],Math.min(...v),Math.max(...v),v.reduce((a,b)=>a+b)/v.length,reqText(reqs[i]),status(v,reqs[i])]));rows.push([],['Par',...definitions.slice(0,6).map(r=>r[0]),'Diámetro conductor 1','Diámetro conductor 2']);result.pairs.forEach((r,i)=>rows.push([i+1,...r.slice(0,6),...r[6]]));rows.push([],['Puntos originales (px)'],['Paso','Punto','X','Y']);steps.forEach((ps,i)=>ps.forEach((p,j)=>rows.push([name(i),j+1,...p])));download(new Blob(['\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'seccion-informe.csv');};
$('png').onclick=()=>{const report=document.createElement('canvas');report.width=1600;const scale=Math.min(1500/photo.width,1100/photo.height),height=photo.height*scale;report.height=Math.ceil(height+510);const c=report.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,report.width,report.height);c.fillStyle='#183236';c.font='bold 32px sans-serif';c.fillText('SECCIÓN · Informe dimensional',50,55);c.font='18px sans-serif';c.fillText(`${config.count} par(es) · Regla: ${config.mm} mm · ${fmt(result.scale)} px/mm`,50,92);c.save();c.translate(50,120);c.scale(scale,scale);c.drawImage(photo,0,0);overlay(c,scale,false);c.restore();let y=height+160;c.font='bold 17px sans-serif';const xs=[50,480,660,840,1020,1390];['Medida (mm)','Mín.','Máx.','Media','Requisito','Estado'].forEach((t,i)=>c.fillText(t,xs[i],y));c.font='17px sans-serif';for(const [i,v] of result.values.entries()){y+=34;[definitions[i][0],fmt(Math.min(...v)),fmt(Math.max(...v)),fmt(v.reduce((a,b)=>a+b)/v.length),reqText(reqs[i]),status(v,reqs[i])].forEach((t,j)=>c.fillText(t,xs[j],y));}c.font='15px sans-serif';c.fillText('Ajustes circulares. Verifica la escala y los contornos. Estados calculados por valor individual.',50,y+55);report.toBlob(blob=>{if(blob)download(blob,'seccion-informe.png');});};
$('pdf').onclick=()=>{fit();window.print();};
controls();
